### PR TITLE
Support Alias Records, Wildcard (* asterisk) Names, and Reference argument

### PR DESCRIPTION
**Pull request by comster**

### CODE REVIEW

**Comment by leorossi** [comment]
LGTM

**Comment by leorossi** [comment]
@chilts this is related also to https://github.com/chilts/nice-route53/issues/19

Could you please have a look and if LGTY merge it, so we will have also a newer `aws-sdk`?

Thanks!

**Comment by chilts** [comment]
It'd be nice to have something in the ReadMe for the alias records. Does anyone feel like doing that? Otherwise I can take a look a some point - just not sure when! :)

**Comment by chilts** [comment]
Released to npm as v1.3.0.

**Pull request merged**
